name: Publish qwc-base-db docker images

on: [push]

jobs:

    build:
      runs-on: ubuntu-latest
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      steps:

      - uses: actions/checkout@master

      - name: Get version tag
        id: get_tag
        run: |
          if [ ${{ endsWith(github.ref, '-lts') }} = true ]; then
            echo "tag=latest-lts,${GITHUB_REF:10}" >>$GITHUB_OUTPUT
          else
            echo "tag=latest,${GITHUB_REF:10}" >>$GITHUB_OUTPUT
          fi

      - name: Build and publish qwc-base-db docker image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: sourcepole/qwc-base-db
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tags: "${{ steps.get_tag.outputs.tag }}"
          workdir: .

      - name: Build and publish qwc-base-db-migrate docker image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: sourcepole/qwc-base-db-migrate
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tags: "${{ steps.get_tag.outputs.tag }}"
          workdir: .
          dockerfile: Dockerfile.migrate
